config/routes.rb
Rails.application.routes.draw do
  get 'activities', to: 'activities#index'
  
  get "activities/index"
  get "home/index"
  root 'home#index'

  get 'home', to: 'pages#home', as: :home

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get 'register', to: 'registrations#new', as: :new_registration
  post 'register', to: 'registrations#create'

  get 'profile', to: 'users#show', as: :profile
  get 'profile/edit', to: 'users#edit', as: :edit_profile
  patch 'profile', to: 'users#update'

  get 'confirm_email/:token', to: 'users#confirm_email', as: :confirm_email

  namespace :admin do
    resources :users, only: [:index, :edit, :update, :destroy]
  end

  patch 'make_admin', to: 'users#make_admin', as: :make_admin_profile

  get 'join_group', to: 'groups#join'
  post 'join_group', to: 'groups#join_group'

  resources :groups do
    member do
      delete 'leave_group'
    end
    resources :tasks do
      member do
        patch 'update_status'
        get 'edit_status'
      end
    end
    resources :resources, except: [:show]
    member do
      patch 'promote_to_admin'
      delete 'kick_user'
    end
  end
  
  resources :tasks do
    resources :comments, only: [:create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :task
  belongs_to :usera
  validates :body, presence: true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :tasks, dependent: :destroy
  belongs_to :creator, class_name: 'User'

  has_many :group_memberships, dependent: :destroy
  has_many :users, through: :group_memberships

  has_many :group_admins_memberships, -> { where(admin: true) }, class_name: 'GroupMembership'
  has_many :group_admins, through: :group_admins_memberships, source: :user

  validates :name, presence: true

  has_many :resources, dependent: :destroy

  after_create :make_creator_admin

  def admin?(user)
    group_admins.include?(user)
  end
  
  private

  def make_creator_admin
    group_membership = GroupMembership.find_or_create_by(user: creator, group: self)
    group_membership.update(admin: true)
  end
end

app/models/group_membership.rb
class GroupMembership < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/member.rb
class Member < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/resource.rb
class Resource < ApplicationRecord
  validates :name, presence: true
  has_many :task_resources
  has_many :tasks, through: :task_resources
  belongs_to :group
  has_and_belongs_to_many :tasks
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :assigned_user, class_name: 'User', optional: true
  has_many :comments, dependent: :destroy
  belongs_to :group
  has_and_belongs_to_many :resources
  
  validates :title, :description, :due_date, presence: true
  validates :status, presence: true

  enum status: { offen: 0, in_bearbeitung: 1, erledigt: 2 }

  attribute :status_comment, :string
  has_paper_trail
end

app/models/task_resource.rb
class TaskResource < ApplicationRecord
  belongs_to :task
  belongs_to :resource
end

app/models/user.rb
class User < ApplicationRecord
  validates :email, presence: true, uniqueness: true
  validates :password, length: { minimum: 12 }, allow_nil: true

  has_secure_password

  attr_accessor :current_password
  
  enum role: { user: 0, admin: 1 }
  
  def display_role
    if admin?
      "Premium"
    else
      "Basic"
    end
  end

  has_many :group_memberships
  has_many :groups, through: :group_memberships
  has_many :created_groups, class_name: 'Group', foreign_key: 'creator_id'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @groups = current_user.groups if logged_in?
    @activities = PaperTrail::Version.order(created_at: :desc).limit(10)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_group
  before_action :set_task, only: [:edit, :update, :destroy, :update_status]
  before_action :require_login
  
  def index
    @group = Group.find(params[:group_id])
    @tasks = @group.tasks
  end

  def new
    @task = @group.tasks.build
    @group = Group.find(params[:group_id])
  end

  def create
    @task = @group.tasks.build(task_params)
    @group = Group.find(params[:group_id])
    @task.user_id = current_user.id
    @task.status ||= "offen"
  
    if @task.save
      redirect_to group_tasks_path(@group), notice: 'Aufgabe erfolgreich erstellt.'
    else
      render :new
    end
  end

  def edit
    @group = Group.find(params[:group_id])
    @task = @group.tasks.find(params[:id])
  end

  def update
    @group = Group.find(params[:group_id])
    @task = @group.tasks.find(params[:id])
    @task.status ||= "offen"
    
    if @task.update(task_params)
      redirect_to group_tasks_path(@group), notice: 'Aufgabe erfolgreich aktualisiert.'
    else
      render :edit
    end
  end

  def destroy
    if @group.admin?(current_user)
      @task.destroy
      redirect_to group_tasks_path(@group), notice: 'Aufgabe erfolgreich gelöscht.'
    else
      redirect_to group_tasks_path(@group), alert: 'Nur Gruppenadministratoren können Aufgaben löschen.'
    end
  end

  def update_status
    @task = @group.tasks.find(params[:id])
    
    if @task.update(status: params[:task][:status], status_comment: params[:task][:status_comment])
      redirect_to group_tasks_path(@group), notice: 'Status und Kommentar erfolgreich aktualisiert.'
    else
      render :edit_status
    end
  end
  
  def edit_status
    @group = Group.find(params[:group_id])
    @task = @group.tasks.find(params[:id])
  end

  private

  def set_group
    @group = Group.find(params[:group_id])
  end

  def set_task
    @task = @group.tasks.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:title, :description, :due_date, :assigned_user_id, :status, :status_comment, resource_ids: [])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_login
 
  def show
    @user = current_user
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user

    if params[:user][:password].present?
      unless @user.authenticate(params[:user][:current_password])
        flash.now[:alert] = 'Aktuelles Passwort ist falsch.'
        render :edit and return
      end
    end

    if params[:user][:email] != @user.email
      @user.new_email = params[:user][:email]
      @user.email_confirmation_token = SecureRandom.hex(10)
      if @user.save
        confirmation_link = confirm_email_url(@user.email_confirmation_token)
        Rails.logger.debug "Bestätigungslink: #{confirmation_link}"
        flash[:notice] = 'E-Mail-Bestätigung gesendet. Überprüfe deine neue E-Mail-Adresse.'
        render :edit and return
      end
    end

    if @user.update(user_params.except(:current_password))
      flash[:notice] = 'Profil erfolgreich aktualisiert.'
      redirect_to profile_path
    else
      flash.now[:alert] = 'Profilaktualisierung fehlgeschlagen.'
      render :edit
    end
  end

  def confirm_email
    @user = User.find_by(email_confirmation_token: params[:token])

    if @user && @user.update(email: @user.new_email, new_email: nil, email_confirmation_token: nil)
      redirect_to profile_path, notice: 'E-Mail-Adresse erfolgreich bestätigt.'
    else
      redirect_to profile_path, alert: 'Ungültiger oder abgelaufener Bestätigungslink.'
    end
  end
  
  def make_admin
    @user = current_user
    if @user.update(role: :admin)
      redirect_to profile_path, notice: 'Herzlichen Glückwunsch! Sie haben jetzt Premium rechte.'
    else
      redirect_to profile_path, alert: 'Fehler beim Aktualisieren der Rolle.'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password)
  end

  def require_login
    unless logged_in?
      redirect_to login_path, alert: 'Bitte loggen Sie sich ein, um fortzufahren.'
    end
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>HomeAssist</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <%= javascript_include_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<body>
    <div class="container mt-5">
        <%= yield %>
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

app/views/pages/home.html.erb
<!DOCTYPE html>
<html lang="de">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>HomeAssist</title>
    <%= stylesheet_link_tag "home", media: "all", "data-turbo-track": "reload" %>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-custom">
        <a class="navbar-brand" href="#">HomeAssist</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <div class="navbar-toggler" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        <span class="navbar-toggler-icon"></span>
        <span class="navbar-toggler-icon"></span>
        </div>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="<%= profile_path %>">Profil</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="<%= groups_path %>">Gruppenverwaltung</a>
                </li>
                <li>
                    <a class="nav-link" href="<%= activities_path %>">Aktivitäten-Feed</a>
                </li>
                <li class="nav-item">
                    <%= button_to 'Logout', logout_path, method: :delete, class: 'nav-link btn btn-link logout-btn', data: { confirm: 'Möchtest du dich wirklich ausloggen?' }, form: { class: 'd-inline' } %>
                </li>
            </ul>
        </div>
    </nav>

    <div class="container mt-5">
        <h1 class="text-center">Willkommen auf der Hauptseite, <%= current_user.name %></h1>

        <div class="row justify-content-center">
            <div class="col-lg-10">
                <div class="group-list mt-5">
                    <h2 class="text-center">Deine Gruppen</h2>
                    <ul class="list-group list-group-flush">
                        <% seen_group_ids = Set.new %>
                        <% current_user.groups.each do |group| %>
                            <% unless seen_group_ids.include?(group.id) %>
                                <li class="list-group-item mb-4">
                                    <div class="group-info">
                                        <h5 class="group-name">Gruppe: <%= group.name %></h5>
                                    </div>
                                    <h6>Verwalten</h6>
                                    <a href="<%= group_tasks_path(group) %>" class="btn btn-secondary btn-block mb-2">Aufgaben ansehen/ verwalten</a>
                                    <a href="<%= group_resources_path(group) %>" class="btn btn-secondary btn-block mb-2">Ressourcen ansehen/ verwalten</a>
                                    <a href="<%= group_path(group) %>" class="btn btn-secondary btn-block mb-2">Mitglieder ansehen/ verwalten</a>
                                </li>
                                <% seen_group_ids.add(group.id) %>
                            <% end %>
                        <% end %>
                    </ul>
                </div>
            </div>
        </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.2/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</body>
</html>

app/views/resources/edit.html.erb
<!DOCTYPE html>
<html lang="de">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ressource bearbeiten</title>
    <%= stylesheet_link_tag "home", media: "all", "data-turbo-track": "reload" %>
</head>
<body>

    <div class="edit-resource-container">
        <h1>Ressource bearbeiten</h1>

        <%= form_with(model: [@group, @resource], local: true) do |form| %>
            <div class="form-group">
                <%= form.label :name, "Name der Ressource", class: "form-label" %>
                <%= form.text_field :name, class: "form-control" %>
            </div>

            <div class="form-group">
                <%= form.label :description, "Beschreibung", class: "form-label" %>
                <%= form.text_area :description, class: "form-control" %>
            </div>

            <div class="form-group">
                <%= form.label :quantity, "Menge", class: "form-label" %>
                <%= form.number_field :quantity, class: "form-control" %>
            </div>

            <div class="form-buttons">
                <%= form.submit "Speichern", class: "custom-btn btn-success" %>
                <%= link_to 'Zurück', group_resources_path(@group), class: "custom-btn btn-secondary" %>
            </div>
        <% end %>

    </div>

</body>
</html>

app/views/resources/index.html.erb
<!DOCTYPE html>
<html lang="de">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ressourcen in der Gruppe <%= @group.name %></title>
    <%= stylesheet_link_tag "home", media: "all", "data-turbo-track": "reload" %>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-custom">
        <a class="navbar-brand" href="#">HomeAssist</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <div class="navbar-toggler" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        <span class="navbar-toggler-icon"></span>
        <span class="navbar-toggler-icon"></span>
        </div>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ml-auto">
                <li>
                    <a class="nav-link" href="<%= home_path %>">Zur Hauptseite</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="<%= profile_path %>">Profil</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="<%= groups_path %>">Gruppenverwaltung</a>
                </li>
                <li>
                    <a class="nav-link" href="<%= activities_path %>">Aktivitäten-Feed</a>
                </li>
                <li class="nav-item">
                    <%= button_to 'Logout', logout_path, method: :delete, class: 'nav-link btn btn-link logout-btn', data: { confirm: 'Möchtest du dich wirklich ausloggen?' }, form: { class: 'd-inline' } %>
                </li>
            </ul>
        </div>
    </nav>

    <div class="resources-container">
        <h1>Ressourcen in der Gruppe <%= @group.name %></h1>
        <div class="form-buttons">
            <%= link_to 'Neue Ressource erstellen', new_group_resource_path(@group), class: 'custom-btn btn-success' %>
        </br></br>

        </div>
         <div class="table-responsive">
            <table class="table table-striped table-hover">
                <thead class="table-dark">
                <tr>
                    <th>Ressourcenname</th>
                    <th>Menge</th>
                    <th>Aktionen</th>
                </tr>
            </thead>
            <tbody>
                <% @resources.each do |resource| %>
                    <tr>
                        <td><strong><%= resource.name %></strong></td>
                        <td><%= resource.quantity %></td>
                        <td>
                            <% if @group.admin?(current_user) %>
                                <div class="d-flex gap-2">
                                    <%= link_to 'Bearbeiten', edit_group_resource_path(@group, resource), class: 'custom-btn btn-primary' %>
                                    <%= button_to 'Löschen', group_resource_path(@group, resource), method: :delete, data: { confirm: 'Möchtest du diese Ressource wirklich löschen?' }, class: 'btn btn-danger' %>
                                </div>
                            <% else %>
                                <p>Nur Haushaltsmanagers können Ressourcen bearbeiten oder löschen.</p>
                            <% end %>
                        </td>
                    </tr>
                <% end %>
            </tbody>
        </table>
       </div>
    </div>
</body>
</html>

app/views/resources/new.html.erb
<!DOCTYPE html>
<html lang="de">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Neue Ressource für Gruppe: <%= @group.name %></title>
    <%= stylesheet_link_tag "home", media: "all", "data-turbo-track": "reload" %>
</head>
<body>

    <div class="new-resource-container">
        <h1>Neue Ressource für Gruppe: <%= @group.name %></h1>

        <%= form_with(model: [@group, @resource], local: true) do |form| %>
            <div class="form-group">
                <%= form.label :name, "Ressourcenname", class: "form-label" %>
                <%= form.text_field :name, class: "form-control" %>
            </div>
			
			<div class="form-group">
			     <%= form.label :quantity, "Menge", class: "form-label" %>
			     <%= form.number_field :quantity, class: "form-control" %>
			</div>

            <div class="form-buttons">
                <%= form.submit "Ressource erstellen", class: "custom-btn btn-success" %>
                <%= link_to 'Zurück', group_resources_path(@group), class: 'custom-btn btn-secondary' %>
            </div>
        <% end %>

    </div>

</body>
</html>